[target.thumbv8m.main-none-eabihf]
runner = "sudo picotool load -u -v -x -t elf"
# runner = "./scripts/flash_and_log.sh"

rustflags = [
    # "-C", "link-arg=-Tlink.x",
    "-C", "target-cpu=cortex-m33",
]

[build]
target = "thumbv8m.main-none-eabihf"
